Run linter with prettier 2
exceljs/exceljs pull request #1477
Opened 2020-09-28 10:28 UTC by alubbe

## Summary

Some files haven't had the linter applied to, so let's fix that :)

## Test plan

No new tests are needed

2020-09-28 12:55 UTC, Siemienik requested changes
This pr again introduce lots of changes, which has no sense. Lets we keep current style rules

2020-09-28 18:18 UTC, alubbe commented
Agreed - I've reset the arrow-parens behaviour back to prettier v1 ('as-needed'). The other changes were always 'wrong', I think and they looks safe enough to merge

2020-09-28 19:46 UTC, Siemienik requested changes
I've added more comments, If is it fine to you I'm going to propose some rules changes according to my comments 😉

2020-09-28 19:46 UTC, Siemienik commented on lib/utils/under-dash.js
> -    return html
I might it is a regression

2020-09-28 19:46 UTC, Siemienik commented on lib/csv/csv.js
> -  .extend(customParseFormat)
for me it a one step backward

2020-09-28 19:46 UTC, Siemienik commented on lib/xlsx/xform/sheet/cf-ext/conditional-formattings-ext-xform.js
> +const CompositeXform = require('../../composite-xform');
what was done here?

2020-09-28 19:46 UTC, Siemienik commented on lib/xlsx/xform/sheet/cf/conditional-formattings-xform.js
> +const BaseXform = require('../../base-xform');
what was done here?

2020-09-28 19:46 UTC, Siemienik commented on spec/integration/issues/issue-1328-xlsx-worksheet-reader-date.spec.js
> +  beforeEach(
could you ignore this rule? imo, before was better

2020-09-28 19:46 UTC, Siemienik commented on spec/unit/xlsx/xform/compy-xform.js
> +const BaseXform = verquire('xlsx/xform/base-xform');
what was done here?

2020-09-28 19:46 UTC, Siemienik commented on spec/unit/xlsx/xform/table/auto-filter-xform.spec.js
> +const testXformHelper = require('../test-xform-helper');
what was done here?

2020-09-28 19:46 UTC, Siemienik commented on spec/unit/xlsx/xform/table/filter-column-xform.spec.js
> +const testXformHelper = require('../test-xform-helper');
what was done here?

2020-09-28 19:46 UTC, Siemienik commented on spec/unit/xlsx/xform/table/table-column-xform.spec.js
> +const testXformHelper = require('../test-xform-helper');
what was done here?

2020-09-28 19:46 UTC, Siemienik commented on spec/unit/xlsx/xform/table/table-style-info-xform.spec.js
> +const testXformHelper = require('../test-xform-helper');
what was done here?

2020-09-28 19:46 UTC, Siemienik commented on spec/unit/xlsx/xform/table/table-xform.spec.js
> +const fs = require('fs');
an the last time, what was done here?

2020-09-28 20:54 UTC, Siemienik commented on lib/xlsx/xform/sheet/cf/conditional-formattings-xform.js
> +const BaseXform = require('../../base-xform');
break line style

2020-09-28 20:58 UTC, Siemienik approved these changes
After some investigation, I changed max-len option to 100. Before was 160 - that value is too much for properly priettier 2 working. 

As effect some improvements was introduced like:

https://github.com/exceljs/exceljs/pull/1477/files#diff-a083b92106d7d843e5f325cb350dbf25L102-R109

2020-09-29 06:49 UTC, alubbe commented
Looks good, I also found another typo

2020-09-29 07:26 UTC, merged