Fix issue 174 (to check invalid sheet name)
exceljs/exceljs pull request #1484
Opened 2020-10-02 00:20 UTC by skypesky

## Summary

Fix issue #1474 .
An exception is thrown when the name is illegal.

## Test plan

For this I have added unit tests.

2020-10-02 04:33 UTC, papb commented
Hello! I suggest you take a look [at this](https://github.com/papb/json-excel/blob/master/source/assert-valid-sheet-names.ts), do you think it would be good to also add these other checks?

2020-10-02 05:12 UTC, skypesky commented
hi,papb,Your method is more concise, I think it's very good.
I didn't write according to the assertvalidsheetname method before, because the validation of name in the original code did not always throw an exception. In this way, how to organize it becomes very strange.

About double quotation marks
---
It seems that the naming rules of sheet have something to do with the version of Excel

As for single quotation marks
---
As far as I know, single quotation marks can be placed in the middle, but not the head and tail. Can you test the single quotation marks for me?

2020-10-02 12:26 UTC, alubbe requested changes

2020-10-02 12:26 UTC, alubbe commented on spec/integration/worksheet.spec.js
> +      it('when the worksheet name contain < > * ? " | : / \\ [ ]', () => {
this should be `it('throws an error'...)`

2020-10-02 12:26 UTC, alubbe commented on spec/integration/worksheet.spec.js
> +        const invalideNames = ['*', '?', ':', '/', '\\', '[', ']'];
please call this `invalidCharacters`

2020-10-02 12:26 UTC, alubbe commented on lib/doc/workbook.js
> +    return /(\*)|(\?)|(:)|(\/)|(\\)|(\[)|(\])/.test(sheetName);
please use the simpler and faster regex `/[*?:\/\\\[\]]/` instead

2020-10-05 07:38 UTC, alubbe requested changes
Just some minor feedback around the readability/maintainability of the test case, then we're good to go!

2020-10-05 07:38 UTC, alubbe commented on spec/integration/worksheet.spec.js
> +        const expectedErrors = invalidNames.map(
I think the array creation and the for-index-loop distract a little bit from what is being tested, I think we should simplify to this:
```js
for (const invalidName of invalidNames) {
  expect(() => workbook.addWorksheet(invalidName)).to.throw(
    `The first or last character of worksheet name cannot be a single quotation mark: ${invalidName}`
  );
}
```

2020-10-05 07:38 UTC, alubbe commented on spec/integration/worksheet.spec.js
> +        const expectedErrors = invalidCharacters.map(
I think the array creation and the for-index-loop distract a little bit from what is being tested, I think we should simplify to this:
```js
for (const invalidCharacter of invalidCharacters) {
  expect(() => workbook.addWorksheet(invalidCharacter)).to.throw(
    `Worksheet name ${invalidCharacter} cannot include any of the following characters: * ? : \\ / [ ]`
  );
}
```

2020-10-05 10:21 UTC, alubbe approved these changes
thank you!

2020-10-05 10:21 UTC, merged

2023-11-06 03:21 UTC, Sczlog commented
Although here has been a long long times since this change applied.
But I suppose if replace invalid character with `_` should be a better choice?
Current solution is kinda a breaking change, code running successful (but not correct?) before will break after update to later version.